# Generated by Django 2.2.7 on 2020-02-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RV', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default=6, max_length=50),
            preserve_default=False,
        ),
    ]
